# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - function-tatsukoni-test-v3

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)
  RESOURCE_GROUP_NAME: 'tatsukoni-test-v1'
  FUNCTION_NAME: 'function-tatsukoni-test-v3'
  SLOT_NAME: 'staging'

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.FUNCTION_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8DF5DC8F7C8448189F86C85F569C57FB }}

  swap-production:
    needs: build-and-deploy-staging
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_FUNCTION_DEMO_V3 }}

      - name: 'Swap Azure Function To Production'
        id: slot_swap
        run: |
          az webapp deployment slot swap \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --name ${{ env.FUNCTION_NAME }} \
            --slot ${{ env.SLOT_NAME }}

      - name: 'Logout via Azure CLI'
        run: |
          az logout
